version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 854383975731.dkr.ecr.ap-south-1.amazonaws.com
      - REPO_URI=854383975731.dkr.ecr.ap-south-1.amazonaws.com/test-01
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Writing image definitions...
      - printf '[{"name":"Test-cluster","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
