version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 120569649088.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=120569649088.dkr.ecr.ap-south-1.amazonaws.com/dev
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - ls -lrt
      - docker --version
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t dev:latest .
      - docker tag dev:latest 120569649088.dkr.ecr.ap-south-1.amazonaws.com/dev:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 120569649088.dkr.ecr.ap-south-1.amazonaws.com/dev
      - printf '[{"name":"Dev","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinations.json
      - cat imagedefinations.json
artifacts:
  files: imagedefinations.json
