version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  ApplicationStop:
    - location: kill_container.sh
  BeforeInstall:
    - location: before_script.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_script.sh
      timeout: 300
      runas: root

